<h1> Install SpeckCommerce </h1>
<?php
$directory = 'config';
$dbconfig  = 'config/autoload/database.local.php'; // todo: check if db config exists and connection works, display details used for install instead of form
?>
<?php if(!is_writable($directory)): ?>
    <h3 style="color:#ff5555;">cannot write to config directory</h3>
    <h5> - please fix permissions, or ensure you have copied+configured the db config file manually before you continue</h5>
<?php endif ?>

<form method="post" action="/install/schema">
<div class="row">
    <div class="span3">
        <input class="span3" name="site_name" placeholder="website name" type="text"   />
    </div>
</div>
<br/><br/>
<p>MySQL User and Database must be configured prior to this step</p>
<div class="row">
    <div class="span2">
        <input class="span2" name="host" placeholder="host address" type="text" value="localhost"/>
    </div>
    <div class="span1">
        <input class="span1" name="port" placeholder="port" type="text" value="3306"/>
    </div>
</div>
<div class="row">
    <div class="span3">
        <input class="span3" name="user" placeholder="mysql user" type="text" value="speck"    />
    </div>
</div>
<div class="row">
    <div class="span3">
        <input class="span3" name="pass" placeholder="mysql password" type="text" />
    </div>
</div>
<div class="row">
    <div class="span3">
        <input class="span3" name="db_name" placeholder="database name" type="text" value="speck"    />
    </div>
</div>
<div class="row">
    <div class="span3">
        <button class="btn" id="test_connection" onClick="alert('not implemented yet'); return false">Test Connection</button>
        <input type="submit" class="btn btn-primary" value="Next"/>
    </div>
</div>
</form>
